CHANGELOG.md, drivers/mysql/internal_test.go, drivers/mysql/mysql.go
=> MySQL DSN no longer strips driver options

.golangci.yml, drivers/mysql/internal_test.go, drivers/mysql/metadata.go, drivers/mysql/mysql.go, drivers/mysql/sqlbuilder.go
Misc linting for drivers/mysql
=> Misc linting and code tidy

CHANGELOG.md, README.md, cli/completion.go
=> '__complete sql @offline_handle' no longer errors, but instead returns the handle

.github/workflows/go.yml, .goreleaser.yml, aura/install.sh, install.sh
- goreleaser now releases Arch Linux artifacts to AUR
- `install.sh` now installs for Arch Linux
=> Install for Arch Linux

cli/output/adapter.go, drivers/csv/csv_test.go, drivers/csv/detect_field_kinds.go, drivers/csv/import.go, drivers/csv/insert.go, drivers/sqlite3/sqlite3.go, libsq/core/kind/detect.go, libsq/core/kind/munge.go, libsq/core/lg/lga/lga.go, libsq/driver/driver.go, testh/record.go, testh/sakila/sakila.go
=> CSV empty string now treated as NULL

.github/workflows/main.yml, README.md
https://github.com/GoTestTools/gotestfmt-action
=> Workflow: add gotestfmt

cli/cli.go, cli/cmd_config.go, cli/cmd_config_get.go, cli/cmd_config_set.go, cli/complete.go, cli/config/store.go, cli/config/yamlstore/defaultload.go, cli/config/yamlstore/testdata/good.01.sq.yml, cli/config/yamlstore/upgrade.go, cli/config/yamlstore/yamlstore.go, cli/config/yamlstore/yamlstore_test.go, cli/flag/flag.go, cli/options.go, cli/output/format/format.go, cli/output/jsonw/configw.go, cli/output/printing.go, cli/output/tablew/configw.go, cli/output/tablew/sourcewriter.go, cli/output/tablew/tablew.go, cli/output/writers.go, cli/output/yamlw/configw.go, cli/run_test.go, cli/writers.go, drivers/csv/import.go, libsq/core/options/opt.go, libsq/core/options/options.go, libsq/core/options/options_test.go, libsq/driver/driver.go, libsq/driver/tuning.go, testh/testh.go
Implemented `sq config set my.opt 123`.
=> #199: sq config set

CHANGELOG.md, cli/cmd_slq.go, cli/output/csvw/csvwriter.go, cli/output/htmlw/htmlw.go, cli/output/jsonw/recordwriter.go, cli/output/markdownw/markdownw.go, cli/output/raww/raww.go, cli/output/tablew/configwriter.go, cli/output/tablew/recordwriter.go, cli/output/yamlw/recordwriter.go, cli/output/yamlw/yamlw.go, cli/output/yamlw/yamlw_test.go, cli/writers.go
=> #8 : Implemented yaml record writer

CHANGELOG.md, cli/cli.go, cli/cmd_config_edit.go, cli/cmd_diff.go, cli/cmd_ping.go, cli/cmd_root.go, cli/cmd_slq.go, cli/diff/diff.go, cli/diff/source.go, cli/diff/table.go, cli/flag/flag.go, cli/output.go, cli/output/csvw/csvw.go
Further work on `sq diff` #229.
=> #229: Yet more sq diff implementation.

drivers/sqlite3/sqlite3.go, libsq/source/files.go
- Clean up the scratch temp file mechanism.
=> Simplify temp file handling

CHANGELOG.md, libsq/ast/expr.go, libsq/ast/func.go, libsq/ast/node.go, libsq/ast/render/fromtable.go, libsq/ast/selector.go, libsq/engine.go, libsq/prepare.go, libsq/query_join_test.go, libsq/query_test.go
=> #277: Table alias

.github/workflows/test-install.yml, install.sh
=> install.sh: xbps-install (void linux) support

libsq/core/kind/detect.go, libsq/core/kind/kind_test.go
Addendum to PR #336 for issue #335.
=> kind detector now handles decimal.Decimal

cli/cmd_tbl.go, cli/internal_test.go, cli/options.go, cli/options_test.go, drivers/mysql/metadata.go, drivers/postgres/metadata.go, drivers/sqlite3/metadata.go, drivers/sqlite3/pragma.go, drivers/sqlserver/errors.go, drivers/sqlserver/grip.go, drivers/sqlserver/metadata.go, drivers/sqlserver/properties.go, drivers/sqlserver/sqlserver.go, drivers/xlsx/ingest.go, libsq/core/progress/progress.go, libsq/driver/driver.go, libsq/driver/record.go, libsq/libsq.go
- Add progress bars to:
- `sq tbl copy`
- `sq tbl truncate`
- `sq tbl drop`
- Added new config option `progress.OptDebugSleep`
=> More progress bars

libsq/core/ioz/ioz.go, libsq/core/loz/loz.go, libsq/core/loz/loz_test.go
- Some misc io and generic functions.
=> Misc ioz and loz funcs

cli/complete_location_test.go, drivers/csv/csv_test.go, drivers/sqlite3/grip.go, drivers/xlsx/xlsx_test.go, testh/sakila/sakila_test.go, testh/tu/skip.go, testh/tu/tu.go
Adds a mechanism to skip tests when running on windows, specifying a GH issue.
=> tu.SkipIssue mechanism

cli/cmd_x.go, libsq/core/lg/lg_test.go, libsq/files/cache.go, libsq/files/download.go, libsq/files/downloader/cache.go, libsq/files/downloader/downloader.go, libsq/files/downloader/downloader_test.go, libsq/files/files.go
See: https://github.com/neilotoole/sq/actions/runs/7679297142/job/20930035257#step:6:3046
=> Bug with filepath for remote file

cli/config/yamlstore/upgrades/v0.34.0/upgrade_test.go, cli/testrun/testrun.go, drivers/csv/csv_test.go, libsq/core/lg/lgt/lgt.go, libsq/files/cache.go, libsq/files/files_test.go, libsq/files/internal/downloader/downloader_test.go, testh/testh.go, testh/tu/tu.go, testh/tu/tu_test.go
See: https://github.com/neilotoole/sq/actions/runs/7703270004/job/20993307672#step:6:2820
=> More file closing issues (test)

CHANGELOG.md, cli/cmd_root.go, cli/flag/flag.go, cli/options.go, cli/options_test.go, cli/output.go, cli/output/jsonw/metadatawriter.go, cli/output/jsonw/sourcewriter.go, cli/output/printing.go, cli/output/tablew/metadatawriter.go, cli/output/tablew/sourcewriter.go, cli/output/yamlw/metadatawriter.go, cli/output/yamlw/sourcewriter.go
- Added config option `redact` to control password redaction.
- Also available as global flag `--no-redact`.
=> Redaction config

CHANGELOG.md, cli/cmd_add.go, cli/cmd_diff.go, cli/cmd_ping.go, cli/cmd_root.go, cli/cmd_slq.go, cli/cmd_sql_test.go, cli/complete.go, cli/config/store.go, cli/logging.go, cli/options.go, cli/options_test.go, cli/output.go, cli/output/format/opt.go, cli/output/outputx/outputx.go, cli/output/tablew/errorwriter.go, cli/output/xlsxw/datetime.go, drivers/csv/ingest.go, libsq/core/options/opt.go, libsq/core/options/options_test.go, libsq/core/progress/progress.go, libsq/driver/ingest.go, libsq/driver/opts.go, libsq/driver/record.go, libsq/files/cache.go, libsq/files/download.go, libsq/files/internal/downloader/downloader.go
=> Options refactoring

CHANGELOG.md, cli/cmd_diff.go, cli/diff/tabledata.go, cli/output/printing.go, cli/output/tablew/tablediff.go, drivers/mysql/metadata.go, drivers/mysql/mysql.go, drivers/postgres/metadata.go, drivers/postgres/postgres.go, drivers/sqlite3/metadata.go, drivers/sqlite3/pragma.go, drivers/sqlite3/sqlite3.go, drivers/sqlserver/metadata.go, drivers/sqlserver/properties.go, drivers/sqlserver/sqlserver.go, libsq/core/oncecache/oncecache_test.go, libsq/core/record/record.go, libsq/core/sqlz/sqlz.go, libsq/core/tailbuf/internal_test.go, libsq/core/tailbuf/tailbuf.go, libsq/core/tailbuf/tailbuf_test.go, libsq/driver/opts.go, libsq/libsq.go
- Improved `record.Equal` behavior
- Fixed bug with `diff.max-hunk-size` adjacent hunks
- More functionality (and tests) for `tailbuf`
=> Fixes and improvements for diff

.github/workflows/codacy.yml, .github/workflows/codeql.yml, .github/workflows/main.yml
Upgrade deprecated workflow action versions.
=> Workflow action version update

.github/workflows/main.yml
It's time to upgrade the GH workflow runner versions.
=> GH workflow runner version upgrade

README.md, install.sh
=> Switch brew to use core formula #467
